### ISSUE TITLE
Need help to compile

### ISSUE THREAD

**Issue by HanFa** [CuSO4Gem/jrme#2]
需要补充的内容：编译的环境，gcc的版本号之类

**Comment by 5o1** [comment]
邮件已收到。本人不常使用邮箱因此推荐您使用别的方法联系。只是推荐哦。

**Comment by CuSO4Gem** [comment]
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0

**Comment by 5o1** [comment]
邮件已收到。本人不常使用邮箱因此推荐您使用别的方法联系。只是推荐哦。
